#!/usr/bin/env bash

# This script is only used for temp fix.
# Try use derviation and AutoPatchelfHook

FILE=$1
echo "Print linked libs:"
patchelf --print-needed $FILE
echo "---"
echo "Print linked interpreter:"
patchelf --print-interpreter $FILE
echo "---"
echo "Print ldd:"
ldd $FILE
echo "---"
nix-shell -p stdenv --run "patchelf --set-interpreter \$(cat \$NIX_CC/nix-support/dynamic-linker) $FILE"
echo "Print linked interpreter again:"
patchelf --print-interpreter $FILE
echo "---"
