#!/usr/bin/env bash
set -e

ENV=$1
if [[ $ENV != "dev" ]] && [[ $ENV != "prod" ]]; then
	echo "only 'dev' or 'prod' supported."
	exit 1
fi
if [[ ! -f "$HOME/Downloads/$ENV.ovpn" ]]; then
	echo "$ENV.ovpn not found."
	exit 1
fi
mkdir -p /tmp/openvpn/
mv ~/Downloads/$ENV.ovpn /tmp/openvpn/$ENV.ovpn
